local-phone-apps := ApplicationsProvider \
		    BackupRestoreConfirmation \
		    CameraTestApp \
		    CertInstaller \
		    CompatibilityMode \
		    DefaultContainerService \
		    DoubleTapWakeup \
		    DrmProvider \
		    FaceLock \
		    GnssAirTest \
		    GnssPosTest \
		    GnssTest \
		    HiddenMenu \
		    KeyChain \
		    LteConfigs \
		    LGBluetooth4 \
		    LGEIME_THEME_ZEEBLACK \
		    LGLiveWallpapersPicker \
		    LGSlideAside \
		    LGQRemote \
		    SystemUI_Provider \
		    LgNfc \
		    PermissionToAccessLgeApi \
		    QuicksetSDK \
		    MediaUploader \
		    MediaProvider \
		    NetworkLocation \
		    SharedStorageBackup \
		    SplitWindowService \
		    Stk \
		    TimeService \
		    UnifiedEULA \
		    UserDictionaryProvider \
		    VpnDialogs \
		    WAPPushManager \
		    WapService \
		    WiseScreen \
		    com.qualcomm.location \
		    com.qualcomm.services.location \
		    qcrilmsgtunnel