local-phone-apps := ApplicationsProvider \
		    CertInstaller \
		    DrmService \
		    DocumentsUI \
		    FaceLock \
		    GnssAirTest \
		    GnssPosTest \
		    GnssTest \
		    GpsBTWIFI \
		    HiddenMenu \
		    InterfacePermissions
		    KeyChain \
		    LGApduService \
		    LGBluetooth4 \
		    LGEIME \
		    LGEIME_THEME_ZEEBLACK \
		    LGFmRadio \
		    LGPCSuiteUI \
		    LGQRemote \
		    LGSmartcardService \
		    LGSystemServer \
		    LgNfc \
		    LicenseProvider \
		    LteConfigs \
		    PacProcessor \
		    PermissionToAccessLgeApi \
		    PrintSpooler \
		    QcomQMIPermissions \
		    QuicksetSDK \
		    SVIService \
		    Stk \
		    TimeService \
		    UnifiedEULA \
		    UserDictionaryProvider \
		    WAPPushManager \
		    WfdService \
		    com.lge.shutdownmonitor \
		    com.qualcomm.location \
		    com.qualcomm.services.location \
		    qcrilmsgtunnel \
		    shutdownlistener